name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Setup Java
      uses: actions/setup-java@v6
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@13.5
      with:
        lein: latest
    - name: Install dependencies
      run: lein deps
    - name: Run cljfmt
      run: lein cljfmt check
